name: Unit Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  unit-test:
    name: Run test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest
        run: pytest
        env:
          JIRA_URL: https://test.atlassian.net
          JIRA_EMAIL: test@test.com
          JIRA_TOKEN: fake-token
          JIRA_PROJECT: SCRUM
          SPRINT_NAME: Sprint 4
          GITHUB_TOKEN: fake-github-token
          DISCORD_BOT_TOKEN: fake-token-for-tests
          GUILD_ID: "0"